### ISSUE TITLE
cap at ep. 26?

### ISSUE THREAD

**Issue by Spamfolder** [lap00zza/Grabber#13]
**Select your issue type:** (check at least one)
- [x] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
is the cap at episode 26?
there are several with 50 + episodes (even good ones),please make it a higher cap,thank you

**Comment by lap00zza** [comment]
Hi. There is no capping within the code (its open source 😄 you can take a look). And here is a image of me grabbing 76 links from [Hajime No Ippo](https://9anime.to/watch/hajime-no-ippo.lr3)

![](https://image.ibb.co/kKww9a/links.png)

Can you tell me in which anime you got capped at 26? I will take a look.

**Comment by Spamfolder** [comment]
the last i tried was gintama, filtered to 720, and no matter if i tried serverwise or the all button  upside,
jdl only got 26,every single time.. 

edit/
tried again, it says count to 51,but it gives out only up to 26 even in clipboard

**Comment by lap00zza** [comment]
That's very weird. Can you please share the link? I will definitely try to find out whats wrong.

#### Edit
Found the link (https://9anime.to/watch/gintama.7wkj). Will update once I find whats wrong.

#### Update
For the link above, in my browser I was able to grab all 51 links from server F2 and F4 (Chrome 59, Windows 8.1). However I think I understand what the problem is. See the way Grabber behaves when you select a quality is like this:

**Consider the selected quality is 720p**
* Grabber sends a request to 9anime API
* 9anime responds with a bunch of quality for that episode (ex: 360p, 480p etc)
* Sometimes the quality you selected may not be present in this returned list. At this point Grabber **does not fall back to the next lower quality** (If you or anyone can help with this that will be cool) and **skips that episode entirely**. This behavior can be seen here: https://github.com/lap00zza/Grabber/blob/master/src/index.js#L177

I hope I answered your question.

#### Update 1
I have attached links for all 51 episodes (720p) below for Gintama'. Enjoy! (*They might not be all valid since they seemed to be tied to ip but do give it a try*)
[Gintama'_Server_F4.txt](https://github.com/lap00zza/Grabber/files/1141969/Gintama._Server_F4.txt)

**Comment by Spamfolder** [comment]
sure
https://9anime.to/watch/gintama0-dub.q3wj/71ko7j

**Comment by lap00zza** [comment]
Its as I explained 1 comment above. I checked your link. **Episode 27 onwards** there are **no 720p links** (only 360p and 480p links are present). You  can test this yourself. Go to any episode (ex: episode 28) and check if it has 720p in the quality select.

![](https://image.ibb.co/b6V6QF/gintamalinks.png)

Grabber can only grab links that 9anime has 😄

**Comment by lap00zza** [comment]
@yumiris do you think a message should be displayed when grabber fails to find the preferred quality?

**Comment by Spamfolder** [comment]
*facepalm* ok, i didnt check if they have 27+ a 720sh, sorry,but i was wondering myself,i tried 2 others just now,and they came thru easy,..yes your script is flawless
can i make a suggestion, a (X) function "best possible resolution", so it takes 720 and the few missing..or half of it, in next lower,might be troublesome to make,but its worth to ask.
however in every single other smaller series,that thing leeches flawless,thanks for that.

**Comment by lap00zza** [comment]
@Spamfolder haha yeah we were discussing that right now. Would you mind making a separate issue for that? That way it will be easier to keep track

**Comment by Spamfolder** [comment]
can do,thanks again,sorry for bothering you with that usererror.

**Comment by lap00zza** [comment]
@Spamfolder you didn't bother at all. This led to a good talk about fallbacks 😄 
If you have any more suggestions remember to file an issue.
