### ISSUE TITLE
No links in link box after grabber is done retrieving links on large animes.

### ISSUE THREAD

**Issue by PriveKoomans** [lap00zza/Grabber#18]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Whenever I want to grab links from large animes, the grabber starts retrieving links but the link box is completely empty after it's finished grabbing.

Example: https://9anime.to/watch/dgray-man.q3j
![knipsel](https://user-images.githubusercontent.com/31109613/30001654-11842f8c-9094-11e7-8d73-23af7237fa2f.PNG)

**Comment by lap00zza** [comment]
@PriveKoomans hello. I checked that link out. It looks like D.GRAY-MAN does not have 1080p episodes. It seems to have only 360p and 480p episodes. That's why you are getting a blank box. Grabber does not support fallback (meaning if 1080p is missing try 720p). 

My suggestions:
1. Try lowering the quality (360p or 480p)
2. Try using my other project https://github.com/lap00zza/9anime-Companion. It supports fallback and adds quite a lot of other features to 9anime.

Fallback for Grabber is being worked on in https://github.com/lap00zza/Grabber/tree/feature/fallback_quality, with a open issue #14

**Comment by PriveKoomans** [comment]
Hello, thanks for answering so quick :)

My mistake, I didn't look any further than what was right in front of me. 

I suggest putting something like "It seems there were no links found related to this quality, please try a lower quality instead." in the linkbox if nothing is found though so dumb people like me don't start asking dumb questions hahaha.

**Comment by lap00zza** [comment]
😄 will surely do. If you need any more please feel free to re-open this issue.
